export interface GalleryItem {
  id: string;
  src: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  category: "aerea" | "cocho" | "manejo" | "embarque" | "institucional" | "animais";
}

export const gallery = [
  {
    id: "lote-cruzamento-descanso",
    src: "/gallery/2022-06-30_19-15-32.jpg",
    alt: "Lote de animais de cruzamento industrial no confinamento",
    caption: "Piquete de confinamento com animais em terminação",
    width: 1080,
    height: 810,
    category: "animais",
  },
  {
    id: "aerea-clementina-pens",
    src: "/gallery/2022-07-01_19-19-51.jpg",
    alt: "Vista aérea dos currais da Unidade Clementina",
    caption: "Unidade Clementina - SP",
    width: 768,
    height: 768,
    category: "aerea",
  },
  {
    id: "confina-brasil-scot",
    src: "/gallery/2022-07-08_13-30-58.jpg",
    alt: "Placa oficial de certificação Confina Brasil Scot Consultoria",
    caption: "Certificação Confina Brasil · Scot Consultoria",
    width: 739,
    height: 406,
    category: "institucional",
  },
  {
    id: "aerea-sertaozinho-panoramica",
    src: "/gallery/2022-07-13_19-51-58_1.jpg",
    alt: "Vista aérea panorâmica da Unidade Sertãozinho",
    caption: "Unidade Sertãozinho - SP",
    width: 579,
    height: 328,
    category: "aerea",
  },
  {
    id: "aerea-sertaozinho-entardecer",
    src: "/gallery/2022-07-13_19-51-58_2.jpg",
    alt: "Vista aérea do confinamento Sertãozinho ao entardecer",
    caption: "Operação Sertãozinho ao entardecer",
    width: 579,
    height: 328,
    category: "aerea",
  },
  {
    id: "aerea-sertaozinho-corredores",
    src: "/gallery/2022-07-13_19-51-58_3.jpg",
    alt: "Vista aérea das linhas de piquetes e corredores de trato",
    caption: "Linhas de confinamento e corredores de alimentação",
    width: 579,
    height: 328,
    category: "aerea",
  },
  {
    id: "aerea-sertaozinho-topdown",
    src: "/gallery/2022-07-13_19-51-58_4.jpg",
    alt: "Vista aérea superior dos módulos de confinamento",
    caption: "Estrutura modular de piquetes",
    width: 579,
    height: 328,
    category: "aerea",
  },
  {
    id: "aerea-sertaozinho-galpao",
    src: "/gallery/2022-07-13_19-51-58_5.jpg",
    alt: "Estrutura de armazenagem de insumos e fábrica de ração",
    caption: "Fábrica de ração e centro de distribuição de insumos",
    width: 579,
    height: 328,
    category: "aerea",
  },
  {
    id: "lote-angus-ceu-azul",
    src: "/gallery/2022-07-15_21-19-35_1.jpg",
    alt: "Lote de cruzamento industrial de alto padrão genético sob céu azul",
    caption: "Genética e nutrição de precisão",
    width: 768,
    height: 576,
    category: "animais",
  },
  {
    id: "lote-angus-sertaozinho",
    src: "/gallery/2022-07-15_21-19-35_2.jpg",
    alt: "Lote de animais Angus em terminação na Unidade Sertãozinho",
    caption: "Nutrição e desenvolvimento · Unidade Sertãozinho",
    width: 1080,
    height: 810,
    category: "animais",
  },
  {
    id: "curral-manejo-seringa",
    src: "/gallery/2022-07-15_21-19-35_3.jpg",
    alt: "Curral de manejo e seringa de direcionamento do gado",
    caption: "Manejo racional e controle individual",
    width: 960,
    height: 720,
    category: "manejo",
  },
  {
    id: "embarque-abate-rampa",
    src: "/gallery/2022-07-15_21-19-35_7.jpg",
    alt: "Embarque de animais terminados para o abate",
    caption: "Embarque e expedição de lotes terminados",
    width: 960,
    height: 720,
    category: "embarque",
  },
  {
    id: "boiada-nelore-frente",
    src: "/gallery/2022-07-20_12-14-08.jpg",
    alt: "Boiada Nelore uniforme na Unidade Sertãozinho",
    caption: "Lote Nelore em ponto de terminação",
    width: 1080,
    height: 810,
    category: "animais",
  },
  {
    id: "piquete-nelore-cocho",
    src: "/gallery/2022-07-21_17-20-42.jpg",
    alt: "Piquete de confinamento junto à linha de cocho",
    caption: "Piquete com linha de cocho e bebedouros",
    width: 1080,
    height: 810,
    category: "cocho",
  },
  {
    id: "acabamento-carcaca",
    src: "/gallery/2022-08-31_19-03-54.jpg",
    alt: "Acabamento de carcaça e conformação frigorífica",
    caption: "Acabamento de carcaça · Unidade Sertãozinho",
    width: 1024,
    height: 648,
    category: "animais",
  },
  {
    id: "angus-destaque-piquete",
    src: "/gallery/2022-10-15_00-30-10.jpg",
    alt: "Animais Angus e cruzamento em primeiro plano",
    caption: "Padrão de carcaça e uniformidade de lote",
    width: 1080,
    height: 810,
    category: "animais",
  },
  {
    id: "aerea-sales-represa",
    src: "/gallery/2023-04-11_18-19-49.jpg",
    alt: "Vista aérea de alta resolução da Unidade Sales com represa ao fundo",
    caption: "Unidade Sales - SP (Fazenda Tabaju)",
    width: 1080,
    height: 807,
    category: "aerea",
  },
  {
    id: "aerea-sertaozinho-agrishow",
    src: "/gallery/2023-04-13_02-38-32.jpg",
    alt: "Vista aérea da Unidade Sertãozinho próxima à Agrishow",
    caption: "Unidade Sertãozinho · Região de Ribeirão Preto",
    width: 828,
    height: 466,
    category: "aerea",
  },
  {
    id: "lote-bois-pretos-sunset",
    src: "/gallery/2023-04-20_16-52-02.jpg",
    alt: "Lote de animais pretos confinados ao entardecer",
    caption: "Confinamento ao entardecer",
    width: 1080,
    height: 565,
    category: "animais",
  },
  {
    id: "cocho-concreto-alimentacao",
    src: "/gallery/2023-05-03_16-47-18.jpg",
    alt: "Gado consumindo matéria seca na linha de cocho de concreto",
    caption: "Manejo de cocho e leitura de consumo diário",
    width: 1080,
    height: 593,
    category: "cocho",
  },
  {
    id: "cocho-nelore-vertical",
    src: "/gallery/2023-06-21_18-15-46.jpg",
    alt: "Linha contínua de cocho com gado Nelore ao entardecer",
    caption: "Nutrição contínua no sistema por matéria seca",
    width: 1080,
    height: 1350,
    category: "cocho",
  },
  {
    id: "aerea-modulos-canavial",
    src: "/gallery/2025-04-23_16-16-57_1.jpg",
    alt: "Vista aérea ampla dos módulos de confinamento e canaviais",
    caption: "Capacidade estática e estrutura operacional",
    width: 1080,
    height: 608,
    category: "aerea",
  },
  {
    id: "aerea-macro-arvore-central",
    src: "/gallery/2025-04-23_16-16-57_2.jpg",
    alt: "Visão aérea panorâmica do confinamento Maximus Agronegócio",
    caption: "Complexo de terminação Maximus Agronegócio",
    width: 1080,
    height: 610,
    category: "aerea",
  },
  {
    id: "aerea-corredor-trato",
    src: "/gallery/2025-04-23_16-16-57_3.jpg",
    alt: "Vista aérea longitudinal da avenida central de distribuição de ração",
    caption: "Logística de distribuição de matéria seca",
    width: 1080,
    height: 610,
    category: "cocho",
  },
  {
    id: "aerea-panoramica-geral",
    src: "/gallery/2025-04-23_16-16-57_4.jpg",
    alt: "Visão panorâmica aérea do complexo e relevo da região",
    caption: "Infraestrutura integrada no interior paulista",
    width: 1080,
    height: 607,
    category: "aerea",
  },
  {
    id: "lote-gado-ancp-conecta",
    src: "/gallery/2026-03-27_19-03-47_10.jpg",
    alt: "Lote de animais Nelore no piquete em primeiro plano",
    caption: "Manejo com foco em conversão alimentar",
    width: 1079,
    height: 719,
    category: "animais",
  },
  {
    id: "sede-fachada-oficial",
    src: "/gallery/2026-03-27_19-03-47_5.jpg",
    alt: "Fachada oficial da sede administrativa da Maximus Agronegócio",
    caption: "Sede administrativa · Maximus Agronegócio",
    width: 1079,
    height: 719,
    category: "institucional",
  },
  {
    id: "logo-maximus-nova-fase",
    src: "/gallery/2026-05-13_11-39-33.jpg",
    alt: "Identidade visual Maximus Agronegócio",
    caption: "Maximus Agronegócio · Nova Fase",
    width: 1080,
    height: 1080,
    category: "institucional",
  },
  {
    id: "equipe-sede-visita-tecnica",
    src: "/gallery/2026-06-18_15-27-58.jpg",
    alt: "Equipe técnica e pecuaristas parceiros em frente à sede",
    caption: "Visita técnica e relacionamento com pecuaristas",
    width: 1080,
    height: 1080,
    category: "institucional",
  },
  {
    id: "placa-unidade-sales-tabaju",
    src: "/gallery/2026-07-08_11-41-36.jpg",
    alt: "Placa oficial de boas-vindas da Unidade Fazenda Tabaju em Sales SP",
    caption: "Entrada oficial · Unidade Sales - SP (Fazenda Tabaju)",
    width: 1080,
    height: 1440,
    category: "institucional",
  },
  {
    id: "logo-avatar-oficial",
    src: "/gallery/2026-07-14_14-36-21_UTC_profile_pic.jpg",
    alt: "Símbolo oficial Maximus Agronegócio",
    caption: "Maximus Agronegócio",
    width: 320,
    height: 320,
    category: "institucional",
  },
] as const;

export type GalleryId = (typeof gallery)[number]["id"];

export const galleryMap = Object.fromEntries(
  gallery.map((item) => [item.id, item])
) as Record<GalleryId, GalleryItem>;

